services:
  next-app:
    container_name: svg_to_code_next-app
    build:
      context: ./app
      dockerfile: dev.Dockerfile

    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - svg_network

networks:
  svg_network:
    external: true
